CREATE TABLE IF NOT EXISTS products (
 id SERIAL PRIMARY KEY, name VARCHAR(180) NOT NULL, slug VARCHAR(220) UNIQUE NOT NULL,
 category VARCHAR(80) NOT NULL, description TEXT, price NUMERIC(12,2) NOT NULL,
 old_price NUMERIC(12,2), image_url TEXT, stock INTEGER NOT NULL DEFAULT 0,
 rating NUMERIC(2,1) NOT NULL DEFAULT 5, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS customers (
 id SERIAL PRIMARY KEY, name VARCHAR(150) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 phone VARCHAR(40) NOT NULL, address TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS orders (
 id SERIAL PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id), reference VARCHAR(120) UNIQUE NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'pending', payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
 payment_reference VARCHAR(150), total NUMERIC(12,2) NOT NULL DEFAULT 0, currency CHAR(3) NOT NULL DEFAULT 'NGN',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS order_items (
 id SERIAL PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
 product_id INTEGER NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL CHECK(quantity>0), unit_price NUMERIC(12,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_orders_reference ON orders(reference);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
